import cx_Freeze
import sys
import os

os.environ['TCL_LIBRARY'] = "C:\\Users\\soderstromk\\AppData\\Local\\Programs\\Python\\Python35\\tcl\\tcl8.6" #C:\Users\soderstromk\AppData\Local\Programs\Python\Python35\tcl\tcl8.6
os.environ['TK_LIBRARY'] = "C:\\Users\\soderstromk\\AppData\\Local\\Programs\\Python\\Python35\\tcl\\tk8.6"

base = None

if sys.platform == 'win32':
    base = "Win32GUI"

executables = [cx_Freeze.Executable("KLFromSAPTables.py", base=base)]

cx_Freeze.setup(
	name = "KLFromSAPTables",
	options = {"build_exe": {"packages":["tkinter","numpy","openpyxl"], "include_files": 'C:\\Windows\\System32\\userenv.dll'}},
    version = "1.0",
    description = "Calculates KL distances between a template MySQL table and target table(s) generated by SAP 2011",
    executables = executables
    )